export const AUTH_JWT_SECRET = "AUTH_JWT_SECRET";
export const SESSION_DYNAMO_TABLE = "SESSION_DYNAMO_TABLE";
export const USER_DYNAMO_TABLE = "USER_DYNAMO_TABLE";
export const WORKSPACE_DYNAMO_TABLE = "WORKSPACE_DYNAMO_TABLE";
